name: Run HVCC
description: 'Runs the hvcc compiler for Pure Data patches. See https://github.com/Wasted-Audio/hvcc for more information about hvcc.'
inputs:
  pd-file:
    description: 'Path to the .pd file to serve as input to hvcc'
    required: true
  output-patch-name:
    description: 'Output patch name (-n argument to hvcc)'
    required: true
  generator:
    description: 'The hvcc generator to use (-g argument to hvcc)'
    required: true
  search-paths:
    description: 'Any search paths to use for including supplementary pd functionality (-p argument to hvcc)'
    requried: false
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.6'
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run hvcc
      shell: bash
      run: |
        hvcc ${{ inputs.pd-file }} -o ./HeavyBuild/${{ inputs.output-patch-name }} -n ${{ inputs.output-patch-name }} -p ${{ inputs.search-paths }} -g ${{ inputs.generator }}
